#goal definition
string arguments    # The script arguments (rosbag ...)
string folder       # If none is given, the folder is taken from dynamic_reconfigure
---
#result definition
---
#feedback
string stdout
string stderr